#!/bin/bash

if [ -z $1 ]
then
	read -p "Enter github account: " account
else
	account=$1;
fi

mkdir src/$account

wget -N -P src/$account https://api.github.com/users/$account/repos

python getgit.py src/$account

for f in `ls src/$account`;
do
	if [ -d "src/$account/$f" ];
	then
		python grepbugs.py src/$account/$f $account.$f
	fi
done;

